export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/sessions",
    LOGOUT: "/auth/session-revocations",
    ME: "/auth/me",
    REFRESH: "/auth/token-renewals",
    REGISTER: "/auth/registrations",
    VERIFY_REGISTRATION: "/auth/registration-verifications",
    FORGOT_PASSWORD: "/auth/password-resets",
    CHANGE_PASSWORD: "/auth/me/password",
    RESET_PASSWORD: "/auth/password-reset-verifications",
  },
  USERS: {
    BASE: "/users",
    DETAIL: (userId: string) => `/users/${userId}`,
    STATUS: (userId: string) => `/users/${userId}/status`,
  },
  PROFILES: {
    ME: "/users/me",
    AVATAR: "/users/me/avatar",
  },
  ADDRESSES: {
    BASE: "/user-addresses",
    DETAIL: (addressId: string) => `/user-addresses/${addressId}`,
    DEFAULT: (addressId: string) => `/user-addresses/${addressId}/default`,
  },
  CATEGORIES: {
    BASE: "/categories",
    CATALOG: "/categories/catalog",
    DETAIL: (categoryId: string) => `/categories/${categoryId}`,
    STATUS: (categoryId: string) => `/categories/${categoryId}/status`,
  },
  SHOPS: {
    NEARBY: "/shops",
    ME: "/shops/me",
    PROFILE: (shopId: string) => `/shops/${shopId}`,
    REVIEWS: (shopId: string) => `/shops/${shopId}/reviews`,
  },
  SHOP_APPLICATIONS: {
    BASE: "/shop-applications",
    ME: "/shop-applications/me/latest",
    HISTORY: "/shop-applications/me",
    DETAIL: (applicationId: string) => `/shop-applications/${applicationId}`,
    RESUBMIT: (applicationId: string) => `/shop-applications/${applicationId}/revisions`,
    CANCEL: (applicationId: string) => `/shop-applications/${applicationId}/cancellations`,
    REVIEW: (applicationId: string) => `/shop-applications/${applicationId}/reviews`,
  },
  SHOP_STAFFS: {
    LIST: "/shop-staff/shop",
    DETAIL: (staffId: string) => `/shop-staff/${staffId}`,
    ACTIVITY_LOGS: (staffId: string) => `/shop-staff/${staffId}/activity-logs`,
  },
  STAFF_SHOPS: {
    LIST: "/shop-staff/me/shops",
    DETAIL: (shopId: string) => `/shop-staff/me/shops/${shopId}`,
  },
  STAFF_INVITATIONS: {
    BASE: "/staff-invitations",
    ME: "/staff-invitations/me",
    BY_SHOP: "/staff-invitations/shop",
    CANDIDATES: "/staff-invitations/candidates",
    DETAIL: (invitationId: string) => `/staff-invitations/${invitationId}`,
    ACCEPT: (invitationId: string) => `/staff-invitations/${invitationId}/acceptances`,
    DECLINE: (invitationId: string) => `/staff-invitations/${invitationId}/rejections`,
  },
  FLASH_DEALS: {
    NEARBY: "/flash-deals",
    BY_SHOP: (shopId: string) => `/shops/${shopId}/flash-deals`,
    DETAIL: (dealId: string) => `/flash-deals/${dealId}`,
  },
} as const;
