export const APP_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  REGISTER_VERIFY: "/register/verify",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD_VERIFY: "/forgot-password/verify",
  CUSTOMER_LEGACY: "/customer",
  CART: "/cart",
  ACCOUNT: "/account",
  ACCOUNT_PROFILE: "/account/profile",
  ACCOUNT_ORDERS: "/account/orders",
  ACCOUNT_REVIEWS: "/account/reviews",
  ACCOUNT_TRUST_SCORES: "/account/trust-score",
  ACCOUNT_SHOP_APPLICATION: "/account/shop-application",
  ACCOUNT_WORKSPACE: "/account/workspace",
  ACCOUNT_STAFF_INVITATIONS: "/account/staff-invitations",
  ADMIN: "/admin",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_STORES: "/admin/stores",
  ADMIN_SHOP_APPLICATIONS: "/admin/shop-applications",
  STAFF: "/staff",
  STORE_OWNER: "/store-owner",
  NOT_FOUND: "*",
} as const;

export type AppPath = (typeof APP_PATHS)[keyof typeof APP_PATHS];
